spring.application.name=les12-vinylshop-dto

# datasource PostgreSQl
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/les12
spring.datasource.username=postgres
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# generate schema ddl to create tables
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with  after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


client-id = VinylShopBackend
issuer-uri = http://localhost:9090/realms/vinyl-shop
client-secret = JhxNw6n9JEz2tpLh62IPZQuiS0sahkhP
audience = account
spring.security.oauth2.resourceserver.jwt.issuer-uri= ${issuer-uri}
spring.security.oauth2.resourceserver.jwt.audiences= ${audience}

